//  下钻权限字典
export const permissionDict = {
  carSeriesProportion: 'carSeriesProportion', //车系产品好评占比
  prodProportion: 'prodProportion', //产品好评TOP
  regionalServicesProportion: 'regionalServicesProportion', //区域服务好评占比
  servicesProportion: 'servicesProportion', //服务好评TOP
  prod: 'prod', //产品
  services: 'services', //服务
  quality: 'quality', //品质
  unableClassificationStatistics: 'unableClassificationStatistics', //无法评估严重性分类统计
  LowClassificationStatistics: 'LowClassificationStatistics', //低严重性分类统计
  prodNeutralAttentionStatistics: 'prodNeutralAttentionStatistics', //中性分类统计
  prodPositiveAttentionStatistics: 'prodPositiveAttentionStatistics', //正面分类统计
  prodNegativeAttentionStatistics: 'prodNegativeAttentionStatistics', //负面分类统计
  moderateClassificationStatistics: 'moderateClassificationStatistics', //中严重性分类统计
  higherClassificationStatistics: 'higherClassificationStatistics', //较高严重性分类统计
  lowerClassificationStatistics: 'lowerClassificationStatistics', //较低严重性分类统计
  highClassificationStatistics: 'highClassificationStatistics', //高严重性分类统计
  complaintsAgainstUsers: 'complaintsAgainstUsers', //投诉用户
  usersNum: 'usersNum', //用户数
  orderNum: 'orderNum', //单据数
  opinionNum: 'opinionNum', //观点数
  prodRisk: 'prodRisk', //产品风险
  servicesRisk: 'servicesRisk', //服务风险
  qualityRisk: 'qualityRisk', //品质风险
  classificationIndexRanking: 'classificationIndexRanking', //分类指数排行
  prodOpinionTop: 'prodOpinionTop', //产品观点TOP
  servicesOpinionTop: 'servicesOpinionTop', //服务观点TOP
  qualityOpinionTop: 'qualityOpinionTop', //品质观点TOP
  productExpectationDistribution: 'productExpectationDistribution', //产品期待分布
  serviceExpectationDistribution: 'serviceExpectationDistribution', //服务期待分布
  carSeriesAlsoMentionsAnalysis: 'carSeriesAlsoMentionsAnalysis', //本竞品车系同时提及分析
  vocProdRisk: 'vocProdRisk', //产品风险预警
  vocServicesRisk: 'vocServicesRisk', //服务风险预警
  vocQualityRisk: 'vocQualityRisk', //品质风险预警
  highFrequencyComplaintUsers: 'highFrequencyComplaintUsers', //高频投诉用户
  srvPositiveAttentionStatistics: 'srvPositiveAttentionStatistics', //正面分类统计
  srvNeutralAttentionStatistics: 'srvNeutralAttentionStatistics', //中性分类统计
  srvNegativeAttentionStatistics: 'srvNegativeAttentionStatistics' //负面分类统计
}
